import React from "react";
import { formatDateTime } from "../utils/helpers";

export default function ReceiptModal({
  open,
  payment,
  application,
  user,
  onClose,
}) {
  if (!open || !payment) return null;

  const receiptNumber =
    payment.transactionId ||
    payment.id ||
    "—";

  return (
    <div className="modal-overlay">
      <div className="modal-card receipt-modal">
        <div className="receipt-header">
          <div className="brand-box">
            MIDOYOL
          </div>

          <button
            type="button"
            className="modal-close"
            onClick={onClose}
            aria-label="Close receipt"
          >
            ×
          </button>
        </div>

        <div className="receipt-title">
          <span className="eyebrow">
            PAYMENT RECEIPT
          </span>

          <h2>Payment Receipt</h2>

          <p>
            Thank you for using MIDOYOL.
          </p>
        </div>

        <div className="receipt-status">
          <span>✓</span>
          <strong>Payment Confirmed</strong>
        </div>

        <div className="receipt-details">
          <div className="receipt-row">
            <span>Student</span>
            <strong>
              {user?.displayName ||
                user?.email ||
                "Student"}
            </strong>
          </div>

          <div className="receipt-row">
            <span>Email</span>
            <strong>
              {user?.email || "—"}
            </strong>
          </div>

          <div className="receipt-row">
            <span>Application ID</span>
            <strong>
              {application?.applicationNumber ||
                application?.id ||
                payment.applicationId ||
                "—"}
            </strong>
          </div>

          <div className="receipt-row">
            <span>Receipt Number</span>
            <strong>{receiptNumber}</strong>
          </div>

          <div className="receipt-row">
            <span>Payment Type</span>
            <strong>
              {payment.type ||
                "Application Fee"}
            </strong>
          </div>

          <div className="receipt-row">
            <span>Date</span>
            <strong>
              {formatDateTime(
                payment.createdAt
              )}
            </strong>
          </div>
        </div>

        <div className="receipt-total">
          <span>Total Paid</span>

          <strong>
            {payment.amount || 0}{" "}
            {payment.currency || "USD"}
          </strong>
        </div>

        <div className="receipt-actions">
          <button
            type="button"
            className="primary-button"
            onClick={() => window.print()}
          >
            Print Receipt
          </button>

          <button
            type="button"
            className="secondary-button"
            onClick={onClose}
          >
            Close
          </button>
        </div>

        <p className="receipt-note">
          This receipt is generated by MIDOYOL.
        </p>
      </div>
    </div>
  );
}
